# Tugas Kecil 2
### Eksplorasi scikit-learn pada Jupyter Notebook
oleh : <br>
Muhamad Ilyas Mustafa / 13516123 <br>
Adam Fadhel

## 1. Membaca dataset standar iris dan dataset play-tennis

In [17]:
from sklearn import datasets, tree
from sklearn.naive_bayes import GaussianNB
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
import graphviz

Read Iris Dataset

In [29]:
iris = datasets.load_iris()
iris_data = iris.data
iris_target = iris.target
# len(iris_data)
# len(iris_target)
# iris.feature_names
iris_data_frame = pd.DataFrame(
    data=np.c_[iris_data, iris_target], 
    columns=iris.feature_names + ['target'])
iris_data_frame.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0     0.0  
1     0.0  
2     0.0  
3     0.0  
4     0.0

In [30]:
iris_data_frame.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)      target  
count        150.000000  150.000000  
mean           1.199333    1.000000  
std            0.762238    0.819232  
min            0.100000    0.000000  
25%            0.300000    0.000000  
50%            1.300000    1.000000  
75%            1.800000    2.000000  
max            2.500000    2.000000

In [31]:
iris_data_frame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
sepal length (cm)    150 non-null float64
sepal width (cm)     150 non-null float64
petal length (cm)    150 non-null float64
petal width (cm)     150 non-null float64
target               150 non-null float64
dtypes: float64(5)
memory usage: 5.9 KB


Read Play-Tennis Dataset

In [11]:
Location = 'weather.nominal.csv'
play_tennis = pd.read_csv(Location)
play_tennis.head()
# play_tennis.info()
# play_tennis.describe()

outlook temperature humidity  windy play
0     sunny         hot     high  False   no
1     sunny         hot     high   True   no
2  overcast         hot     high  False  yes
3     rainy        mild     high  False  yes
4     rainy        cool   normal  False  yes

In [12]:
play_tennis.describe()

outlook temperature humidity  windy play
count       14          14       14     14   14
unique       3           3        2      2    2
top      rainy        mild     high  False  yes
freq         5           6        7      8    9

In [19]:
play_tennis.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 5 columns):
outlook        14 non-null object
temperature    14 non-null object
humidity       14 non-null object
windy          14 non-null bool
play           14 non-null object
dtypes: bool(1), object(4)
memory usage: 542.0+ bytes


## 2. Melakukan pembelajaran dengan skema full training & tampilkan model

2.1 NaiveBayes

In [33]:
gnb = GaussianNB()
gnb.fit(iris.data, iris.target)

GaussianNB(priors=None, var_smoothing=1e-09)

In [37]:
print("Probabilistic Model")
print("-------------------------------------")
print(gnb.class_prior_)
print("-------------------------------------")
print(gnb.theta_)
print("-------------------------------------")
print(gnb.sigma_)

Probabilistic Model
-------------------------------------
[0.33333333 0.33333333 0.33333333]
-------------------------------------
[[5.006 3.428 1.462 0.246]
 [5.936 2.77  4.26  1.326]
 [6.588 2.974 5.552 2.026]]
-------------------------------------
[[0.121764 0.140816 0.029556 0.010884]
 [0.261104 0.0965   0.2164   0.038324]
 [0.396256 0.101924 0.298496 0.073924]]


2.3 DecisionTree ID3

In [39]:
clf = tree.DecisionTreeClassifier()
clf.fit(iris_data, iris_target)
dot_data = tree.export_graphviz(clf, out_file=None, 
                                feature_names=iris.feature_names, 
                                class_names=iris.target_names, 
                                filled=True, rounded=True, 
                                special_characters=True)  
graph = graphviz.Source(dot_data)
# graph

2.4 kNN

In [41]:
from sklearn.neighbors import KNeighborsClassifier

n = 5
knn = KNeighborsClassifier(n)
knn.fit(iris_data, iris_target)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

2.5 Neural Network MLP

In [46]:
from sklearn.neural_network import MLPClassifier
nnmlp = MLPClassifier()
nnmlp.fit(iris_data, iris_target)

/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)

In [48]:
print("ANN Model")
print(nnmlp.coefs_)
print(nnmlp.intercepts_)

ANN Model
[array([[-6.40293174e-02,  5.41835265e-02, -4.01233302e-03,
        -1.12087291e-03, -9.20850806e-02,  2.24073800e-01,
        -8.51820905e-02, -9.56108491e-02, -8.92058690e-02,
        -3.22374927e-02,  3.78221101e-02, -2.10280904e-03,
        -2.63636503e-02,  2.08022907e-02,  1.42824110e-01,
         9.36042572e-02, -1.06872976e-01, -7.26191290e-02,
        -7.31971253e-02, -7.85688372e-02,  3.94934708e-02,
        -1.55208206e-02,  1.28474635e-01,  1.59106319e-01,
        -1.53559487e-01,  1.12103608e-01,  4.89563945e-04,
         1.85206145e-01, -6.90482221e-03, -6.74387347e-03,
        -7.22995180e-02,  1.76642191e-01, -2.80310773e-02,
         3.56582672e-02,  2.46309370e-01,  2.27763804e-01,
         9.54689557e-02,  3.18646328e-02, -6.32010033e-02,
        -2.08310571e-01, -7.98489617e-02, -2.58847075e-02,
        -5.30916015e-02,  1.03652657e-01, -1.73442194e-01,
        -2.49333221e-04, -7.69065099e-02,  1.32964164e-01,
        -1.04286073e-02,  8.95507165e-03,  1.

## 3. Melakukan pembelajaran untuk dataset iris dengan skema split train 90% dan test 10%

3.1. Naive Bayes

3.2. Decision Tree

3.3. kNN

3.4. Neural Network MLP

## 4. Melakukan pembelajaran untuk dataset iris dengan skema 10-fold cross validation